from fastapi.responses import RedirectResponse
from google_auth_oauthlib.flow import Flow
from fastapi import APIRouter, HTTPException
from googleapiclient.discovery import build
from fastapi import Request
import os
import time

# Disable HTTPS requirement for local development
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

router = APIRouter(prefix="/youtube", tags=["youtube"])

# In-memory storage for playlists (temporary solution until DB is implemented)
playlists_db = {}

def search_youtube(artist, title, youtube):
	query = f"{artist} {title} official audio"

	try:
		search = youtube.search().list(
			part="snippet",
			q=query,
			type="video",
			maxResults=1
		).execute()

		if search.get("items"):
			return search["items"][0]["id"]["videoId"]
		return None
	except Exception as e:
		print(f"Error searching for {artist} - {title}: {e}")
		return None

def add_to_playlist(youtube, playlist_id, video_id):
	try:
		youtube.playlistItems().insert(
			part="snippet",
			body={
				"snippet": {
					"playlistId": playlist_id,
					"resourceId": {
						"kind": "youtube#video",
						"videoId": video_id
					}
				}
			}
		).execute()
		time.sleep(0.5)  # Rate limiting
		return True
	except Exception as e:
		print(f"Error adding video {video_id}: {e}")
		return False


@router.get("/start")
def youtube_start(playlist_id: str):
	client_secrets_file = os.getenv("GOOGLE_CLIENT_SECRETS", "client_secret.json")
	redirect_uri = os.getenv("REDIRECT_URI", "http://localhost:8000/youtube/callback")
	
	flow = Flow.from_client_secrets_file(
		client_secrets_file,
		scopes=["https://www.googleapis.com/auth/youtube"],
		redirect_uri=redirect_uri
	)

	auth_url, _ = flow.authorization_url(
		access_type="offline",
		prompt="consent",
		state=playlist_id
	)

	return RedirectResponse(auth_url)


@router.get("/callback")
def youtube_callback(request: Request):
	client_secrets_file = os.getenv("GOOGLE_CLIENT_SECRETS", "client_secret.json")
	redirect_uri = os.getenv("REDIRECT_URI", "http://localhost:8000/youtube/callback")
	
	flow = Flow.from_client_secrets_file(
		client_secrets_file,
		scopes=["https://www.googleapis.com/auth/youtube"],
		redirect_uri=redirect_uri
	)

	flow.fetch_token(authorization_response=str(request.url))
	credentials = flow.credentials

	playlist_id = request.query_params.get("state")
	
	# Get playlist from temporary storage
	ai_playlist = playlists_db.get(playlist_id)
	if not ai_playlist:
		raise HTTPException(status_code=404, detail="Playlist not found")

	youtube = build("youtube", "v3", credentials=credentials)

	playlist = youtube.playlists().insert(
		part="snippet,status",
		body={
			"snippet": {
				"title": ai_playlist["playlist_name"],
				"description": "Generated by PlayMood AI"
			},
			"status": {"privacyStatus": "private"}
		}
	).execute()

	yt_playlist_id = playlist["id"]

	# Track added videos to avoid duplicates
	added_videos = set()
	success_count = 0

	for track in ai_playlist["tracks"]:
		video_id = search_youtube(track["artist"], track["title"], youtube)
		if video_id and video_id not in added_videos:
			if add_to_playlist(youtube, yt_playlist_id, video_id):
				added_videos.add(video_id)
				success_count += 1
				print(f"✅ Added: {track['artist']} - {track['title']}")

	print(f"\n🎵 Playlist created! Added {success_count}/{len(ai_playlist['tracks'])} songs")
	yt_url = f"https://www.youtube.com/playlist?list={yt_playlist_id}"
	return RedirectResponse(yt_url)
